### ISSUE TITLE
Need binary /  instructions to reload bootloader on Fubarino SD

### ISSUE THREAD

**Issue by davidsmoot** [fubarino/fubarino.github.com#10]
My company bought a half dozen or so Fubarino SD's for a rapid prototype for a customer and they worked great.  However I was running my own native PIC code, not MPIDE code.

My company has no more need for these prototypes and I want to use them to teach basic programming skills to a group of kids.  I want to be able to use them with MPIDE again.  Can you please post / provide binaries and instructions?  I have access to a Pickit  programmer as well as several ICD 3's.
Thanks,
David

**Comment by EmbeddedMan** [comment]
I believe that the original question has been answered here so I'm going to close this issue.
