### ISSUE TITLE
MISO/MOSI incorrect.

### ISSUE THREAD

**Issue by AtomSoftTech** [fubarino/fubarino.github.com#11]
You have this: 
SDO, MISO
SDI, MOSI

When its actually supposed to be:
SDO, MOSI
SDI, MISO

Here: https://github.com/fubarino/fubarino.github.com/wiki/SD-Board-Pin-Features

**Comment by EmbeddedMan** [comment]
Since the documentation is now fixed, I believe, I'm going to close this issue.
