### ISSUE TITLE
not able to debug

### ISSUE THREAD

**Issue by Prasoon7777** [fubarino/fubarino.github.com#16]
hi, in my fubarino mini board debugging is not working. but i am able to program the IC. while trying to debug it is showing an error message 

"Programming/Verify complete"
"The target device is not ready for debugging. Please check your configuration bit settings and program the device before proceeding. The most common causes for this failure are oscillator and/or PGC/PGD settings."

here 8MHz crystal frequency is multiplied to 40MHz using PLL.
I am using MPlabX IDE. i am using PGED1 and PGEC1 for programming. i have also tried with PGED3 and PGEC3 but the result is same error message. 
configuration bit settings that i am using is also given below

// PIC32MX250F128D Configuration Bit Settings

// 'C' source line config statements

#include <xc.h>

// DEVCFG3
// USERID = No Setting
#pragma config PMDL1WAY = OFF           // Peripheral Module Disable Configuration (Allow multiple reconfigurations)
#pragma config IOL1WAY = OFF            // Peripheral Pin Select Configuration (Allow multiple reconfigurations)
#pragma config FUSBIDIO = OFF           // USB USID Selection (Controlled by Port Function)
#pragma config FVBUSONIO = OFF          // USB VBUS ON Selection (Controlled by Port Function)

// DEVCFG2
#pragma config FPLLIDIV = DIV_2         // PLL Input Divider (2x Divider)
#pragma config FPLLMUL = MUL_20         // PLL Multiplier (20x Multiplier)
#pragma config UPLLIDIV = DIV_12        // USB PLL Input Divider (12x Divider)
#pragma config UPLLEN = OFF             // USB PLL Enable (Disabled and Bypassed)
#pragma config FPLLODIV = DIV_1         // System PLL Output Clock Divider (PLL Divide by 1)

// DEVCFG1
#pragma config FNOSC = PRIPLL           // Oscillator Selection Bits (Primary Osc w/PLL (XT+,HS+,EC+PLL))
#pragma config FSOSCEN = OFF            // Secondary Oscillator Enable (Disabled)
#pragma config IESO = OFF               // Internal/External Switch Over (Disabled)
#pragma config POSCMOD = HS             // Primary Oscillator Configuration (HS osc mode)
#pragma config OSCIOFNC = OFF           // CLKO Output Signal Active on the OSCO Pin (Disabled)
#pragma config FPBDIV = DIV_2           // Peripheral Clock Divisor (Pb_Clk is Sys_Clk/2)
#pragma config FCKSM = CSDCMD           // Clock Switching and Monitor Selection (Clock Switch Disable, FSCM Disabled)
#pragma config WDTPS = PS1048576        // Watchdog Timer Postscaler (1:1048576)
#pragma config WINDIS = OFF             // Watchdog Timer Window Enable (Watchdog Timer is in Non-Window Mode)
#pragma config FWDTEN = OFF             // Watchdog Timer Enable (WDT Disabled (SWDTEN Bit Controls))
#pragma config FWDTWINSZ = WINSZ_25     // Watchdog Timer Window Size (Window Size is 25%)

// DEVCFG0
#pragma config JTAGEN = ON              // JTAG Enable (JTAG Port Enabled)
#pragma config ICESEL = ICS_PGx1        // ICE/ICD Comm Channel Select (Communicate on PGEC1/PGED1)
#pragma config PWP = OFF                // Program Flash Write Protect (Disable)
#pragma config BWP = OFF                // Boot Flash Write Protect bit (Protection Disabled)
#pragma config CP = OFF                 // Code Protect (Protection Disabled)

**Comment by EmbeddedMan** [comment]
I think I have found the problem.

You need to change
#pragma config FPLLODIV = DIV_1 // System PLL Output Clock Divider (PLL Divide by 1)
to
#pragma config FPLLODIV = DIV_2 // System PLL Output Clock Divider (PLL Divide by 1)

and then you'll be able to debug. If you look at Figure 6-1 in the Oscillators chapter (chapter 6) of the PIC32 reference manual, you can see that you're taking an 8Mz crystal (on the Fubarino), dividing it by 2 (FPLLIDIV), multiplying it by 20 to get 80MHz (FPLLMUL), then you were trying to use that 80MHz to run your part. These parts are only rated to 50Mhz, so that's why you need to then divide that 80Mhz down by 2 to get 40MHz (FPLLODIV). You can of course try to overclock it past it's rated speed, but then you may run into unexpected problems.

Let me know if that solves the problem for you or not.

*Brian

**Comment by Prasoon7777** [comment]
@EmbeddedMan, Thanks for your valuable support. Its working fine and i am able to debug now.

~Prasoon.

**Comment by EmbeddedMan** [comment]
Great! Closed-
