### ISSUE TITLE
mini schematic shows possible error

### ISSUE THREAD

**Issue by bravo685** [fubarino/fubarino.github.com#17]
On v1.6 mini schematic 5v is connected to pin 42 (vbus) on micro. What would happen if Vin was used and greater than max voltage allowed on vbus input at micro (+5.5v). I think this port should be changed to Vbus instead of the 5v port.

**Comment by EmbeddedMan** [comment]
Yes, good find. I think you're spot on. I'll get that updated.

**Comment by EmbeddedMan** [comment]
Version 1.7 has been created with this change.

**Comment by bravo685** [comment]
Brian,
Thanks for the update.

One question though, doesn't the PIC32MX have an internal clock? Is this a
limitation do to MPIDE not able to set the configuration registrar bits?

Thanks,
Robert

**Comment by EmbeddedMan** [comment]
Robert,

Yes, the PIC32 does have an internal clock. However, it's not accurate
enough to use for USB - not on all systems anyway. So we have to use an
external crystal in order to have the accuracy required by USB.

MPIDE does not set configuration bits - that's done in the bootloader,
which is also available on Github if you want to compile it yourself. (It's
really easy.)

*Brian

**Comment by JacobChrist** [comment]
Brian,

Do you know if the USB stability issue is unique to PIC32?  We have several
PIC18 boards that we use the internal oscillator with USB with no apparent
problem (can't say we have tested over temperature).

Jacob

On Mon, Sep 14, 2015 at 3:14 PM, Brian Schmalz <notifications@github.com>
wrote:

> Robert,
>
> Yes, the PIC32 does have an internal clock. However, it's not accurate
> enough to use for USB - not on all systems anyway. So we have to use an
> external crystal in order to have the accuracy required by USB.
>
> MPIDE does not set configuration bits - that's done in the bootloader,
> which is also available on Github if you want to compile it yourself. (It's
> really easy.)
>
> *Brian
>
> On Mon, Sep 14, 2015 at 5:09 PM, bravo685 <notifications@github.com>
> wrote:
>
> > Brian,
> > Thanks for the update.
> >
> > One question though, doesn't the PIC32MX have an internal clock? Is this
> a
> > limitation do to MPIDE not able to set the configuration registrar bits?
> >
> > Thanks,
> > Robert
> >
> > On Sun, Sep 13, 2015 at 4:52 PM, Brian Schmalz <notifications@github.com
> >
> > wrote:
> >
> > > Version 1.7 has been created with this change.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-139917316
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140219258
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140220378>
> .
>



-- 
Jacob Christ
*ProLinear/PONTECH, Inc.*
1-877-985-9286 Phone
1-413-235-1651 Fax
http://www.pontech.com

**Comment by bravo685** [comment]
Thanks Brian, Understood.

I would be interested in working with the bootloader. I looked over the
project on github and don't see it. Am I overlooking it?

**Comment by JacobChrist** [comment]
https://github.com/chipKIT32/PIC32-avrdude-bootloader

On Mon, Sep 14, 2015 at 3:40 PM, bravo685 <notifications@github.com> wrote:

> Thanks Brian, Understood.
>
> I would be interested in working with the bootloader. I looked over the
> project on github and don't see it. Am I overlooking it?
>
> On Mon, Sep 14, 2015 at 6:14 PM, Brian Schmalz <notifications@github.com>
>
> wrote:
>
> > Robert,
> >
> > Yes, the PIC32 does have an internal clock. However, it's not accurate
> > enough to use for USB - not on all systems anyway. So we have to use an
> > external crystal in order to have the accuracy required by USB.
> >
> > MPIDE does not set configuration bits - that's done in the bootloader,
> > which is also available on Github if you want to compile it yourself.
> (It's
> > really easy.)
> >
> > *Brian
> >
> > On Mon, Sep 14, 2015 at 5:09 PM, bravo685 <notifications@github.com>
> > wrote:
> >
> > > Brian,
> > > Thanks for the update.
> > >
> > > One question though, doesn't the PIC32MX have an internal clock? Is
> this
> > a
> > > limitation do to MPIDE not able to set the configuration registrar
> bits?
> > >
> > > Thanks,
> > > Robert
> > >
> > > On Sun, Sep 13, 2015 at 4:52 PM, Brian Schmalz <
> notifications@github.com
> > >
> > > wrote:
> > >
> > > > Version 1.7 has been created with this change.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-139917316
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140219258
> > >
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140220378
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140225709>
> .
>



-- 
Jacob Christ
*ProLinear/PONTECH, Inc.*
1-877-985-9286 Phone
1-413-235-1651 Fax
http://www.pontech.com

**Comment by EmbeddedMan** [comment]
Jacob,

No, the USB stability issue is not just a PIC32 issue. However, it's not a
blanket thing- you have to research the exact part, and the exact crystal,
in order to see if it will be good enough.

On my UBW board (which was PIC18F2553 based) the built-in RC oscillator was
nowhere near good enough - it wouldn't ever enumerate. So SparkFun built
the first several hundred UBW boards with an external resonator. I tested
many UBWs, and never once had a problem. But users started complaining that
their UBW boards would randomly not work, they had to plug into different
PCs to make them work, they would work for a while but then stop, etc. We
traced it down to the external resonator not being accurate enough to stay
in spec. So we had to move to a real crystal. That stopped all of our
problems.

There are some more recent PICs that have USB that actually get their own
clocks from the USB signal sent by the PC - thus they're always 'accurate'
enough and never need an external crystal.

So you have to do your homework and make sure your crystal and processor
will be in spec across all temps and over aging as well.

*Brian

**Comment by JacobChrist** [comment]
Thanks Brian, good to know.


On Mon, Sep 14, 2015 at 3:52 PM, Brian Schmalz <notifications@github.com>
wrote:

> Jacob,
>
> No, the USB stability issue is not just a PIC32 issue. However, it's not a
> blanket thing- you have to research the exact part, and the exact crystal,
> in order to see if it will be good enough.
>
> On my UBW board (which was PIC18F2553 based) the built-in RC oscillator was
> nowhere near good enough - it wouldn't ever enumerate. So SparkFun built
> the first several hundred UBW boards with an external resonator. I tested
> many UBWs, and never once had a problem. But users started complaining that
> their UBW boards would randomly not work, they had to plug into different
> PCs to make them work, they would work for a while but then stop, etc. We
> traced it down to the external resonator not being accurate enough to stay
> in spec. So we had to move to a real crystal. That stopped all of our
> problems.
>
> There are some more recent PICs that have USB that actually get their own
> clocks from the USB signal sent by the PC - thus they're always 'accurate'
> enough and never need an external crystal.
>
> So you have to do your homework and make sure your crystal and processor
> will be in spec across all temps and over aging as well.
>
> *Brian
>
> On Mon, Sep 14, 2015 at 5:22 PM, Jacob Christ <notifications@github.com>
> wrote:
>
> > Brian,
> >
> > Do you know if the USB stability issue is unique to PIC32? We have
> several
> > PIC18 boards that we use the internal oscillator with USB with no
> apparent
> > problem (can't say we have tested over temperature).
> >
> > Jacob
> >
> > On Mon, Sep 14, 2015 at 3:14 PM, Brian Schmalz <notifications@github.com
> >
>
> >
> > wrote:
> >
> > > Robert,
> > >
> > > Yes, the PIC32 does have an internal clock. However, it's not accurate
> > > enough to use for USB - not on all systems anyway. So we have to use an
> > > external crystal in order to have the accuracy required by USB.
> > >
> > > MPIDE does not set configuration bits - that's done in the bootloader,
> > > which is also available on Github if you want to compile it yourself.
> > (It's
> > > really easy.)
> > >
> > > *Brian
> > >
> > > On Mon, Sep 14, 2015 at 5:09 PM, bravo685 <notifications@github.com>
> > > wrote:
> > >
> > > > Brian,
> > > > Thanks for the update.
> > > >
> > > > One question though, doesn't the PIC32MX have an internal clock? Is
> > this
> > > a
> > > > limitation do to MPIDE not able to set the configuration registrar
> > bits?
> > > >
> > > > Thanks,
> > > > Robert
> > > >
> > > > On Sun, Sep 13, 2015 at 4:52 PM, Brian Schmalz <
> > notifications@github.com
> > > >
> > > > wrote:
> > > >
> > > > > Version 1.7 has been created with this change.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-139917316
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140219258
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140220378
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Jacob Christ
> > *ProLinear/PONTECH, Inc.*
> > 1-877-985-9286 Phone
> > 1-413-235-1651 Fax
> > http://www.pontech.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140222841
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fubarino/fubarino.github.com/issues/17#issuecomment-140227685>
> .
>



-- 
Jacob Christ
*ProLinear/PONTECH, Inc.*
1-877-985-9286 Phone
1-413-235-1651 Fax
http://www.pontech.com
