### ISSUE TITLE
fubarino.github.com/mini/docs/FubarinoMini1_5Diagram.pdf

### ISSUE THREAD

**Issue by JacobChrist** [fubarino/fubarino.github.com#26]
SPI SCK is on the wrong pin.  The picture in the manual appears to be correct (SCK on pin 3/RB14).

The PNG is also wrong:
fubarino.github.com/mini/docs/FubarinoMini1_5Diagram.png

The SVG does appear to be correct.  

Probably just need to regenerate the pdf and png from the svg.

**Comment by EmbeddedMan** [comment]
Confirmed. I will regenerate from the SVG.

Also v2.0 versions are needed (not that they are that different from v1.5)

**Comment by EmbeddedMan** [comment]
Please check the PNG and PDF now. They should be correct. I've also included SVG, PDF and PNG files for FB Mini v2.0 in the same directory, although they're not linked to from anywhere yet. Let me know if you find any problems, or if they all look good, and I'll close this issue out.

**Comment by ApiumJacob** [comment]
Looks good Brian!

**Comment by EmbeddedMan** [comment]
Thanks.
