### ISSUE TITLE
Chip is actually a PIC32mx795f512H not L

### ISSUE THREAD

**Issue by davidsmoot** [fubarino/fubarino.github.com#9]
Your title page and the Microchip website states that it is the L variant but it is actually the H variant.  Which is a huge lucky break for me on a project I am working on that needs the H variant.

**Comment by EmbeddedMan** [comment]
I think this issue has been resolved.

**Comment by davidsmoot** [comment]
it has.  Thank you.

David
On Jan 17, 2015, at 10:22 AM, Brian Schmalz <notifications@github.com> wrote:

I think this issue has been resolved.
